apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    chart: csi-driver-nfs
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.9.0
    helm:
      values: |
        storageClass:
          create: true
          name: nfs-client
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
          parameters:
            server: 192.168.0.160   # REPLACE WITH YOUR TRUENAS IP
            share: /mnt/pool-01/CLUSTER # REPLACE WITH YOUR DATASET PATH
            # This 'subDir' parameter is the secret sauce. 
            # It creates a folder named after the PVC inside your share.
            subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}" 
            mountPermissions: "0777"
          reclaimPolicy: Retain # If you delete the pod, KEEP the data on TrueNAS
          volumeBindingMode: Immediate
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
